### ISSUE TITLE
how can I get this figure

### ISSUE THREAD

**Issue by wangchaowei666** [martinwhl/T-GCN-PyTorch#1]
![image](https://user-images.githubusercontent.com/59414412/119213060-21166d00-baef-11eb-8f25-af01c283f9e1.png)

**Comment by martinwhl** [comment]
You may run `tensorboard --logdir lightning_logs/version_0` to monitor the training progress. When the training process is finished, the prediction results will be generated. Switch to the images panel in tensorboard to view the prediction results.
