### ISSUE TITLE
Muti-feature problem

### ISSUE THREAD

**Issue by Deepyman** [martinwhl/T-GCN-PyTorch#3]
Hi Newbie King, I was wondering if you have time for some direction suggestions. I am trying to use TGCN for muli-variant time-series many2many prediction, but kind of lost in the muti-feature problem. Since when I added more features, the tensor multiple is a little bit abstract and my brain overfitting. Looking forward to your kind reply and I appreciate it in advance.

**Comment by martinwhl** [comment]
An easy solution could be replacing the final output layer with `nn.Linear(hidden_dim, pre_len * num_output_features)`, then reshape the output tensor. I am not sure if it works, but maybe you could give it a try.

**Comment by Deepyman** [comment]
> An easy solution could be replacing the final output layer with `nn.Linear(hidden_dim, pre_len * num_output_features)`, then reshape the output tensor. I am not sure if it works, but maybe you could give it a try.

Thanks for your prompt reply, I didn't state clearly. Actually what I want to do is using TGCN to model a dynamic system, which should give me response by given input. The input is multiple. But the output is 1 dimension. I think the RNN part is little bit easy, because we don't really care the hidden dimension there. But for GCN part, things become tricky, because we have muti-features, they need to multiple with each other carefully.

**Comment by martinwhl** [comment]
> > An easy solution could be replacing the final output layer with `nn.Linear(hidden_dim, pre_len * num_output_features)`, then reshape the output tensor. I am not sure if it works, but maybe you could give it a try.
> 
> Thanks for your prompt reply, I didn't state clearly. Actually what I want to do is using TGCN to model a dynamic system, which should give me response by given input. The input is multiple. But the output is 1 dimension. I think the RNN part is little bit easy, because we don't really care the hidden dimension there. But for GCN part, things become tricky, because we have muti-features, they need to multiple with each other carefully.

In this case, please consider reshaping the input to `(batch_size, seq_len, num_nodes * num_input_features)`.

**Comment by Deepyman** [comment]
> > > An easy solution could be replacing the final output layer with `nn.Linear(hidden_dim, pre_len * num_output_features)`, then reshape the output tensor. I am not sure if it works, but maybe you could give it a try.
> > 
> > 
> > Thanks for your prompt reply, I didn't state clearly. Actually what I want to do is using TGCN to model a dynamic system, which should give me response by given input. The input is multiple. But the output is 1 dimension. I think the RNN part is little bit easy, because we don't really care the hidden dimension there. But for GCN part, things become tricky, because we have muti-features, they need to multiple with each other carefully.
> 
> In this case, please consider reshaping the input to `(batch_size, seq_len, num_nodes * num_input_features)`.

thank you, I will have a try!

**Comment by Deepyman** [comment]
By the way, what is "num_gru_units" in this code, and why         
self.weights = nn.Parameter(
            torch.FloatTensor(self._num_gru_units + 1, self._output_dim)
        )
is this seq_len? Thank you....
